name: Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

permissions: {}

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: >-
      !contains(github.event.pull_request.labels.*.name, 'ðŸ’¥ breaking-change') &&
      !contains(github.event.pull_request.labels.*.name, 'âœ¨ enhancement') &&
      !contains(github.event.pull_request.labels.*.name, 'ðŸž bug') &&
      !contains(github.event.pull_request.labels.*.name, 'ðŸ“– docs') &&
      !contains(github.event.pull_request.labels.*.name, 'chore') &&
      !contains(github.event.pull_request.labels.*.name, 'ðŸ› ï¸ dependencies')
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: 1248576
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - uses: srvaroa/labeler@0a20eccb8c94a1ee0bed5f16859aece1c45c3e55 # v1.13.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
  validate-labels:
    name: check labels missing
    runs-on: ubuntu-latest
    steps:
      - name: check
        if: >-
          !contains(github.event.pull_request.labels.*.name, 'ðŸ’¥ breaking-change') &&
          !contains(github.event.pull_request.labels.*.name, 'âœ¨ enhancement') &&
          !contains(github.event.pull_request.labels.*.name, 'ðŸž bug') &&
          !contains(github.event.pull_request.labels.*.name, 'ðŸ“– docs') &&
          !contains(github.event.pull_request.labels.*.name, 'chore') &&
          !contains(github.event.pull_request.labels.*.name, 'ðŸ› ï¸ dependencies')
        run: >-
          echo One of the following labels is missing on this PR:
          breaking-change enhancement bug docs chore && exit 1
  validate-title:
    name: check title prefix
    runs-on: ubuntu-latest
    steps:
      - name: check
        if: >-
          !startsWith(github.event.pull_request.title, 'fix') &&
          !startsWith(github.event.pull_request.title, 'feat') &&
          !startsWith(github.event.pull_request.title, 'chore') &&
          !startsWith(github.event.pull_request.title, 'docs')
        run: >-
          echo "PR title must start with feat, fix or chore" && exit 1
